kind: pipeline
type: exec
name: default

clone:
  disable: true

steps:
  - name: update
    commands:
      - export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
      - cd /home/$USER/www/${DRONE_REPO_NAME} && git pull

  - name: deploy
    commands:
      - cd /home/$USER/www/${DRONE_REPO_NAME}
      - npm i
      - npm run generate
    depends_on:
      - update

  - name: notify
    commands:
      - echo "Success build by ${DRONE_COMMIT_AUTHOR_EMAIL}"
    depends_on:
      - deploy

trigger:
  branch:
    - master
