kind: pipeline
type: exec
name: default

clone:
  disable: true

steps:
  - name: update
    commands:
      - cd /home/$USER/www/${DRONE_REPO_NAME} && git pull

  - name: deploy
    commands:
      - export PM2_HOME=/home/$USER/.pm2
      - cd /home/$USER/www/${DRONE_REPO_NAME}
      - yarn
      - yarn build
      - pm2 restart memorandum
    depends_on:
      - update

  - name: notify
    commands:
      - echo "Success build by ${DRONE_COMMIT_AUTHOR_EMAIL}"
    depends_on:
      - deploy

trigger:
  branch:
    - master
