kind: pipeline
type: exec
name: default

clone:
  disable: true

steps:
  - name: update
    commands:
      - echo $USER
      - cd /home/$USER/www/${DRONE_REPO_NAME} && git pull
      - echo "$PATH"

  - name: deploy
    commands:
      - export PATH=$PATH/home/ewilan/.nvm/versions/node/v16.13.0/bin
      - cd /home/$USER/www/${DRONE_REPO_NAME}
      - npm i
      - npm run generate
    depends_on:
      - update

  - name: notify
    commands:
      - echo "Success build by ${DRONE_COMMIT_AUTHOR_EMAIL}"
    depends_on:
      - deploy

trigger:
  branch:
    - master
