// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayoutContent: typeof import('./components/layout/content.vue')['default']
    LayoutDirectoryList: typeof import('./components/layout/directory-list.vue')['default']
    LayoutMain: typeof import('./components/layout/main.vue')['default']
    LayoutSidebar: typeof import('./components/layout/sidebar.vue')['default']
    LayoutSidebarStatic: typeof import('./components/layout/sidebar-static.vue')['default']
  }
}

export { }
